theme = "onedark"
[editor]
soft-wrap.enable = true
line-number = "relative"
end-of-line-diagnostics = "hint"
true-color = true

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
space.m = "@miw:sh man 3 %{selection}<ret>"
space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"

[keys.normal."+"]
m = ":run-shell-command make"

[editor.cursor-shape]
insert = "bar"
